<?xml version="1.0"?>
<package format="3">
  <name>aqua_resq</name>
  <version>0.0.0</version>
  <description>AQUA-RESQ ROS2 simulation and perception package</description>

  <maintainer email="snigdha@example.com">Snigdha Bhamidipati</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>px4_msgs</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
